# Generated by Django 5.2 on 2025-04-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField(null=True)),
                ('difficulty', models.IntegerField(null=True)),
                ('importance', models.IntegerField(null=True)),
                ('task_type', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('is_exam_task', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('exam', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Calendar.schedule')),
            ],
        ),
    ]
