# Generated by Django 5.2 on 2025-04-10 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='exam',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Calendar.schedule'),
        ),
    ]
