# Generated by Django 5.2 on 2025-04-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_alter_schedule_deadline_alter_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isfixed',
            field=models.BooleanField(default=False),
        ),
    ]
