# Generated by Django 5.2 on 2025-04-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_schedule_isfixed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='isfixed',
            new_name='is_fixed',
        ),
    ]
