# Generated by Django 5.2 on 2025-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0007_schedule_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
