# Generated by Django 5.2 on 2025-05-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0009_alter_schedule_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Calendar.scheduletype'),
        ),
    ]
