# Generated by Django 5.2 on 2025-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0010_alter_schedule_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='task_type_old',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
