# Generated by Django 5.2 on 2025-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0011_schedule_task_type_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='task_type_old',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='task_type',
            field=models.CharField(blank=True, default='aa', max_length=50),
            preserve_default=False,
        ),
    ]
