# Generated by Django 5.2 on 2025-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0012_remove_schedule_task_type_old_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
