# Generated by Django 4.2.21 on 2025-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0014_alter_schedule_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
